[build]
  command = "npm run build"
  publish = "dist/demo/browser"
  functions = "src/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
